In [22]:
import numpy as np

In [31]:
A = np.array([
    [1,2,3],
    [4,2,5],
    [5,7,4]
])

In [32]:
B = np.array([[4,2,1],[7,3,1],[5,4,6]])

In [33]:
A + B

array([[ 5,  4,  4],
       [11,  5,  6],
       [10, 11, 10]])

In [34]:
A.T

array([[1, 4, 5],
       [2, 2, 7],
       [3, 5, 4]])

In [35]:
3+2*2

7

In [37]:
Name="Michael Jackson"
Name.find('el')

5

In [39]:
A = '1'
B = '2'
int(A) + int(B)

3

In [40]:
int(A+B)

12

In [42]:
a = 'sajaj'
a.upper()

'SAJAJ'

In [43]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [46]:
A=[1,'a']
B=[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

In [48]:
a = set(A)

In [52]:
V = {'A','B'}

V.add('C')
V.add('C')
V

{'A', 'B', 'C'}

In [59]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])